-- 샘플 후보자 3명 생성
-- organization_id와 created_by는 실제 값으로 변경 필요

-- 후보자 1: 시니어 백엔드 개발자
INSERT INTO candidates (
  name,
  email,
  phone,
  location,
  current_company,
  current_position,
  total_experience_years,
  career_summary,
  education,
  skills,
  tech_stack,
  certifications,
  languages,
  desired_position,
  desired_salary,
  desired_location,
  job_search_status,
  strength_summary,
  career_trajectory,
  ideal_roles,
  market_value,
  key_highlights,
  tags,
  status,
  source,
  organization_id,
  created_by
) VALUES (
  '김성준',
  'kim.seongjun@example.com',
  '010-1234-5678',
  '서울 강남구',
  '네이버',
  'Backend Engineer (L4)',
  8,
  '대규모 트래픽 처리 경험이 풍부한 백엔드 엔지니어. MSA 전환 프로젝트 리드 경험 보유. 카카오에서 5년, 네이버에서 3년 근무하며 안정적인 시스템 설계 및 운영 역량 보유.',
  ARRAY['서울대학교 컴퓨터공학과 학사', 'KAIST 전산학과 석사'],
  ARRAY['Java', 'Spring Boot', 'Kotlin', 'MySQL', 'Redis', 'Kafka', 'Kubernetes'],
  ARRAY['Java', 'Spring Boot', 'Kotlin', 'MySQL', 'PostgreSQL', 'Redis', 'Kafka', 'Docker', 'Kubernetes', 'AWS', 'Terraform'],
  ARRAY['정보처리기사', 'AWS Solutions Architect Professional'],
  ARRAY['한국어(원어민)', '영어(비즈니스 회화)'],
  'Staff Backend Engineer',
  '12,000만원',
  '서울 강남/판교',
  '적극적',
  '대규모 분산 시스템 설계 및 운영 전문가. MSA 아키텍처 전환 프로젝트에서 기술 리더십 발휘. 연 1억 트래픽 처리하는 결제 시스템 안정화 경험.',
  '메시징 플랫폼 → 커머스 백엔드 → 결제 시스템으로 커리어 확장. 점진적으로 비즈니스 임팩트가 큰 도메인으로 이동하며 기술적 깊이와 리더십 역량 동시 성장.',
  ARRAY['Staff/Principal Backend Engineer', 'Backend Tech Lead', 'Engineering Manager'],
  '11,000~13,000만원',
  ARRAY['네이버 L4 백엔드 엔지니어 (8년차)', 'MSA 전환 프로젝트 리드', '연 1억 트래픽 결제 시스템 운영', 'Kafka 기반 이벤트 드리븐 아키텍처 설계'],
  ARRAY['Backend', 'MSA', 'High-Traffic', 'Tech-Lead', 'Naver'],
  '서치중',
  '직접등록',
  (SELECT id FROM organizations WHERE name = '테스트조직' LIMIT 1),
  'roche07he@gmail.com'
);

-- 후보자 2: 프론트엔드 리드
INSERT INTO candidates (
  name,
  email,
  phone,
  location,
  current_company,
  current_position,
  total_experience_years,
  career_summary,
  education,
  skills,
  tech_stack,
  certifications,
  languages,
  desired_position,
  desired_salary,
  desired_location,
  job_search_status,
  strength_summary,
  career_trajectory,
  ideal_roles,
  market_value,
  key_highlights,
  tags,
  status,
  source,
  organization_id,
  created_by
) VALUES (
  '박지영',
  'park.jiyoung@example.com',
  '010-2345-6789',
  '서울 서초구',
  '토스',
  'Frontend Chapter Lead',
  6,
  '사용자 경험 개선에 진심인 프론트엔드 리드. React 생태계 전문가로 디자인 시스템 구축 및 성능 최적화 경험 풍부. 크로스팀 협업 능력 우수.',
  ARRAY['이화여대 컴퓨터공학과 학사'],
  ARRAY['React', 'TypeScript', 'Next.js', 'Webpack', 'Storybook', 'Figma'],
  ARRAY['React', 'TypeScript', 'Next.js', 'Vue.js', 'Webpack', 'Vite', 'Storybook', 'Jest', 'Cypress', 'Figma', 'Tailwind CSS'],
  ARRAY['정보처리기사'],
  ARRAY['한국어(원어민)', '영어(비즈니스 유창)'],
  'Frontend Engineering Manager',
  '9,500만원',
  '서울 강남/서초',
  '관심있음',
  '토스 디자인 시스템 v2 구축 리드. 번들 사이즈 40% 감소, 초기 로딩 속도 60% 개선. PM/디자이너와의 원활한 협업으로 정시 런칭 100% 달성.',
  '스타트업 프론트엔드 → 라인 UI 플랫폼 → 토스 Chapter Lead. 개인 기여자에서 팀 리더로 성장하며 기술 전문성과 팀 빌딩 역량 확보.',
  ARRAY['Frontend Lead', 'Frontend Engineering Manager', 'Design System Lead'],
  '8,500~10,000만원',
  ARRAY['토스 Frontend Chapter Lead (6년차)', '디자인 시스템 v2 구축 리드', '번들 사이즈 40% 감소', '크로스팀 협업 프로젝트 다수'],
  ARRAY['Frontend', 'React', 'Design-System', 'Tech-Lead', 'Toss'],
  '서치중',
  '직접등록',
  (SELECT id FROM organizations WHERE name = '테스트조직' LIMIT 1),
  'roche07he@gmail.com'
);

-- 후보자 3: 주니어 풀스택 개발자
INSERT INTO candidates (
  name,
  email,
  phone,
  location,
  current_company,
  current_position,
  total_experience_years,
  career_summary,
  education,
  skills,
  tech_stack,
  certifications,
  languages,
  desired_position,
  desired_salary,
  desired_location,
  job_search_status,
  strength_summary,
  career_trajectory,
  ideal_roles,
  market_value,
  key_highlights,
  tags,
  status,
  source,
  organization_id,
  created_by
) VALUES (
  '이민호',
  'lee.minho@example.com',
  '010-3456-7890',
  '경기도 성남시',
  '컬리',
  'Software Engineer',
  3,
  '빠른 학습 능력과 문제 해결 능력을 갖춘 주니어 풀스택 개발자. 스타트업에서 백엔드/프론트엔드 모두 경험하며 빠르게 성장 중. 적극적인 코드 리뷰 참여와 기술 블로그 운영.',
  ARRAY['연세대학교 컴퓨터과학과 학사'],
  ARRAY['TypeScript', 'Node.js', 'React', 'PostgreSQL', 'Docker'],
  ARRAY['TypeScript', 'JavaScript', 'Node.js', 'Express', 'NestJS', 'React', 'Next.js', 'PostgreSQL', 'MongoDB', 'Docker', 'AWS EC2', 'Git'],
  ARRAY['정보처리기사'],
  ARRAY['한국어(원어민)', '영어(기술 문서 독해 가능)'],
  'Backend Engineer / Fullstack Engineer',
  '6,500만원',
  '서울/판교',
  '적극적',
  '빠른 피드백과 실행력. 신규 기능 개발부터 배포까지 end-to-end 경험 보유. 동료들의 코드 리뷰를 적극 요청하며 빠르게 학습하는 자세.',
  '웹 에이전시에서 풀스택 개발 → 스타트업 백엔드 엔지니어로 커리어 전환. 작은 조직에서 빠르게 성장하며 다양한 기술 스택 경험 중.',
  ARRAY['Backend Engineer', 'Fullstack Engineer', 'Junior Tech Lead'],
  '6,000~7,000만원',
  ARRAY['컬리 주문/결제 시스템 개발', 'Node.js 기반 RESTful API 설계', 'PostgreSQL 쿼리 최적화로 응답속도 30% 개선', '기술 블로그 운영 (월 2회 포스팅)'],
  ARRAY['Backend', 'Fullstack', 'Node.js', 'Junior', 'Kurly'],
  '서치중',
  '직접등록',
  (SELECT id FROM organizations WHERE name = '테스트조직' LIMIT 1),
  'roche07he@gmail.com'
);
